/**
 * a11y-report.ts — Parse accessibility scan JSON results and produce a summary.
 *
 * Usage:
 *   npx tsx scripts/a11y-report.ts [results-dir]
 *
 * Exit codes:
 *   0 — No critical or serious violations
 *   1 — Critical or serious violations found (blocks merge)
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

interface ViolationEntry {
  ruleId: string;
  description: string;
  severity: 'critical' | 'serious' | 'moderate' | 'minor';
  fixSuggestion: string;
  affectedElements: string[];
  helpUrl: string;
}

interface ScanResult {
  url: string;
  pageName: string;
  timestamp: string;
  violations: ViolationEntry[];
  summary: Record<string, number>;
  failed: boolean;
}

const DEFAULT_RESULTS_DIR = path.resolve(
  import.meta.dirname ?? process.cwd(),
  '../apps/web/tests/a11y/results',
);

function main(): void {
  const resultsDir = process.argv[2] ?? DEFAULT_RESULTS_DIR;

  if (!fs.existsSync(resultsDir)) {
    console.log('No results directory found — nothing to report.');
    process.exit(0);
  }

  const files = fs
    .readdirSync(resultsDir)
    .filter((f) => f.endsWith('.json'));

  if (files.length === 0) {
    console.log('No result files found.');
    process.exit(0);
  }

  const totals = { critical: 0, serious: 0, moderate: 0, minor: 0 };
  const allResults: ScanResult[] = [];

  for (const file of files) {
    const raw = fs.readFileSync(path.join(resultsDir, file), 'utf-8');
    const result = JSON.parse(raw) as ScanResult;
    allResults.push(result);

    totals.critical += result.summary['critical'] ?? 0;
    totals.serious += result.summary['serious'] ?? 0;
    totals.moderate += result.summary['moderate'] ?? 0;
    totals.minor += result.summary['minor'] ?? 0;
  }

  // ── Console summary ──
  console.log('\n========================================');
  console.log('  Accessibility Scan Summary');
  console.log('========================================');
  console.log(`  Critical : ${totals.critical}`);
  console.log(`  Serious  : ${totals.serious}`);
  console.log(`  Moderate : ${totals.moderate}`);
  console.log(`  Minor    : ${totals.minor}`);
  console.log('========================================\n');

  // ── Markdown for PR comment ──
  const markdown = buildMarkdown(allResults, totals);
  const mdPath = path.join(resultsDir, 'a11y-summary.md');
  fs.writeFileSync(mdPath, markdown, 'utf-8');
  console.log(`Markdown report written to ${mdPath}`);

  // Also write to GITHUB_STEP_SUMMARY if available
  const summaryFile = process.env['GITHUB_STEP_SUMMARY'];
  if (summaryFile) {
    fs.appendFileSync(summaryFile, markdown, 'utf-8');
    console.log('Appended to GITHUB_STEP_SUMMARY');
  }

  // ── Exit code logic ──
  if (totals.critical > 0 || totals.serious > 0) {
    console.error(
      `BLOCKING: ${totals.critical} critical and ${totals.serious} serious violation(s) found.`,
    );
    process.exit(1);
  }

  if (totals.moderate > 0) {
    console.warn(
      `WARNING: ${totals.moderate} moderate violation(s) — review recommended.`,
    );
  }

  console.log('All clear — no blocking violations.');
  process.exit(0);
}

function buildMarkdown(
  results: ScanResult[],
  totals: Record<string, number>,
): string {
  const lines: string[] = [
    '## Accessibility Scan Results',
    '',
    '| Severity | Count |',
    '|----------|-------|',
    `| Critical | ${totals['critical']} |`,
    `| Serious  | ${totals['serious']} |`,
    `| Moderate | ${totals['moderate']} |`,
    `| Minor    | ${totals['minor']} |`,
    '',
  ];

  const blocking = results.filter((r) => r.failed);

  if (blocking.length > 0) {
    lines.push('### Blocking Violations', '');

    for (const r of blocking) {
      lines.push(`#### ${r.pageName} (\`${r.url}\`)`, '');
      const severe = r.violations.filter(
        (v) => v.severity === 'critical' || v.severity === 'serious',
      );

      for (const v of severe) {
        lines.push(
          `- **[${v.severity.toUpperCase()}]** \`${v.ruleId}\`: ${v.description}`,
          `  - Fix: ${v.fixSuggestion}`,
          `  - Elements: \`${v.affectedElements.join('`, `')}\``,
          `  - [Help](${v.helpUrl})`,
          '',
        );
      }
    }
  } else {
    lines.push('No critical or serious violations found.');
  }

  lines.push(
    '',
    '---',
    '*Generated by nEIP a11y-report*',
  );

  return lines.join('\n');
}

main();
